apiVersion: v1
kind: Pod
metadata:
  name: env-example
spec:
  containers:
  - name: envar-demo-container
    image: busybox
    env:
    - name: ENV_KEYNAME_1
      valueFrom:
      - configMapKeyRef:
        name: log-level-configmap
        key: LOG_LEVEL
    - name: ENV_KEYNAME_2
      valueFrom:
      - configMapKeyRef:
        name: start-k8s
        key: k8s
      