apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - image: mysql
      name: mysql
      env:
        - name: MY_SQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: mysql_secret.conf
        