apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
      
  ports:
    - name: wordpress-port
      port: 80
      nodePort: 32222
  type: NodePort
