apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          resources: # pod의 리소스 제한
            requests: # 최소 요구량
              cpu: 0.1
              memory: 200M
            limits: # 최대 요구량
              cpu: 0.3
              memory: 300M
          ports:
          - containerPort: 80
            name: wordpress-port
--- 

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
      
  ports:
    - name: wordpress-port
      port: 80
      nodePort: 32222
      targetPort: 80
  type: NodePort
