apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
data:
  password: bXkwNTA0

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
  labels:
    app: wordpress
data:
  user: root
