apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      name: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        command: ["/bin/sh", "-ec", "while :; do echo 'Hello world'; sleep 5 ; done"] # pod가 실행시킬 프로세스가 존재하지 않으면 종료하고 다시 pod를 실행시키는 crashLoop가 발생하므로 
        resources:
          requests:
            cpu: "0.1"
            memory: 200M
          limits:
            cpu: "0.2"
            memory: 200M
        volumeMounts:                                                                 # 해당 커맨드로 5초마다 hello world를 출력시켜서 포드를
        - name: mysql-volume
          mountPath: "/etc/mysql-volume" # 컨테이너 내부 "/etc/mysql-volume"에 파일을 마운트. 
          readOnly: true 
      volumes:
      - name: mysql-volume
        secret: 
          secretName: mysql-password